import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Bookknhom</title>
        <meta name="description" content={`This is the Bookknhom page`} />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
